#!/usr/bin/env python3
"""Acceptance entrypoint generator for STPA-Sec Gherkin features.

Reads parser JSON IR and generates thin Python test entry points
that delegate to the acceptance runtime.

Usage:
    generate_entrypoints.py <json-ir> <generated-test-output>
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sys
from pathlib import Path


def _metadata_name(feature_path: str) -> str:
    """Convert feature path to metadata filename."""
    lower = feature_path.lower()
    result = re.sub(r"[^a-z0-9]+", "-", lower)
    return result.strip("-") + ".json"


def generate(ir_path: str, output_dir: str) -> int:
    """Generate acceptance test entry points from JSON IR."""
    ir_file = Path(ir_path)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(ir_file) as f:
        ir = json.load(f)

    feature_name = ir.get("name", "unknown")
    # Create a safe filename from the IR path
    base_name = ir_file.stem
    test_file = out_dir / f"{base_name}_acceptance_test.py"

    # Generate the test file
    test_code = f'''"""Generated acceptance test for {feature_name}.

This file is auto-generated by the acceptance entrypoint generator.
Do not edit manually; regenerate from the JSON IR.
"""

import json
import sys
from pathlib import Path

# Add acceptance runtime to path
_GENERATED_DIR = Path(__file__).resolve().parent
_ACCEPTANCE_DIR = _GENERATED_DIR.parent  # acceptance_runtime.py lives one level up
_PROJECT_ROOT = _ACCEPTANCE_DIR.parents[1] if _ACCEPTANCE_DIR.name == "acceptance" else _GENERATED_DIR.parents[2]
sys.path.insert(0, str(_ACCEPTANCE_DIR))
sys.path.insert(0, str(_PROJECT_ROOT))

from acceptance_runtime import execute_ir


def test_acceptance():
    """Run all acceptance scenarios from the IR."""
    ir_path = Path(r"{ir_file.resolve()}")
    passed, output = execute_ir(str(ir_path))
    assert passed, f"Acceptance tests failed:\\n{{output}}"


if __name__ == "__main__":
    ir_path = Path(r"{ir_file.resolve()}")
    passed, output = execute_ir(str(ir_path))
    print(output)
    sys.exit(0 if passed else 1)
'''

    test_file.write_text(test_code)

    # Compute implementation hash from generated files
    hash_obj = hashlib.sha256(test_file.read_bytes())
    impl_hash = f"sha256:{hash_obj.hexdigest()}"

    # Write metadata
    meta_dir = out_dir / "metadata"
    meta_dir.mkdir(parents=True, exist_ok=True)

    # Derive feature path from IR (best effort)
    feature_path = ir_file.stem.replace("_", " ")

    meta = {
        "schema_version": 1,
        "feature_path": feature_path,
        "ir_path": str(ir_file.resolve()),
        "implementation_hash": impl_hash,
        "hash_scope": "generated_files",
        "generated_files": [str(test_file.relative_to(out_dir))],
    }

    meta_file = meta_dir / _metadata_name(feature_path)
    meta_file.write_text(json.dumps(meta, indent=2))

    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: generate_entrypoints.py <json-ir> <generated-test-output>", file=sys.stderr)
        sys.exit(2)
    sys.exit(generate(sys.argv[1], sys.argv[2]))
