"""Process handler facade for the Phase 4 QA migration."""

from __future__ import annotations

from .phase4_qa_refresh_migration_cli import (
    _h_baseline,
    _h_checks_once,
    _h_endpoint_zero,
    _h_help,
    _h_help_modes,
    _h_help_option,
    _h_identical_checks,
    _h_invalid_invocation,
    _h_invalid_status,
    _h_no_pipeline_child,
    _h_opt_in_unset,
    _h_output_contains,
    _h_run_mode_twice,
    _h_runs_successful,
    _h_standin_count,
    _h_status_zero,
    _h_success_standin,
    _h_summary,
)
from .phase4_qa_refresh_migration_isolation import (
    _h_failure_arguments,
    _h_failure_output_removed,
    _h_failure_root,
    _h_failure_status,
    _h_failure_streams,
    _h_failure_standin,
    _h_failure_summary,
    _h_nested_cwd_unchanged,
    _h_nested_invocation,
    _h_nested_root,
    _h_nested_same,
    _h_nested_static,
    _h_parent_recorded,
    _h_parent_unchanged,
    _h_run_failure_pipeline,
)

__all__ = [
    "_h_baseline",
    "_h_checks_once",
    "_h_endpoint_zero",
    "_h_failure_arguments",
    "_h_failure_output_removed",
    "_h_failure_root",
    "_h_failure_status",
    "_h_failure_streams",
    "_h_failure_standin",
    "_h_failure_summary",
    "_h_help",
    "_h_help_modes",
    "_h_help_option",
    "_h_identical_checks",
    "_h_invalid_invocation",
    "_h_invalid_status",
    "_h_nested_cwd_unchanged",
    "_h_nested_invocation",
    "_h_nested_root",
    "_h_nested_same",
    "_h_nested_static",
    "_h_no_pipeline_child",
    "_h_opt_in_unset",
    "_h_output_contains",
    "_h_parent_recorded",
    "_h_parent_unchanged",
    "_h_run_failure_pipeline",
    "_h_run_mode_twice",
    "_h_runs_successful",
    "_h_standin_count",
    "_h_status_zero",
    "_h_success_standin",
    "_h_summary",
]
