#!/usr/bin/env python3
"""Acceptance entrypoint generator for STPA-Sec Gherkin features.

Reads parser JSON IR and generates thin Python test entry points
that delegate to the acceptance runtime.

Usage:
    generate_entrypoints.py <json-ir> <generated-test-output> [feature-path]
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

from paths import project_root
from snapshot import artifact_paths, metadata_name


def _project_root(start: Path) -> Path:
    """Compatibility wrapper for callers of the old private helper."""
    return project_root(start)


def _sha256_bytes(data: bytes) -> str:
    return f"sha256:{hashlib.sha256(data).hexdigest()}"


def _relative_ir_path(ir_file: Path, root: Path) -> str:
    try:
        return ir_file.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return ir_file.as_posix()


def _feature_path_for(ir_rel: str, feature_path: str | None) -> str:
    if feature_path:
        return Path(feature_path).as_posix()
    from snapshot import snapshot_layout

    layout = snapshot_layout()
    ir_dir = layout.ir_dir
    features_dir = layout.features_dir
    if ir_rel.startswith(f"{ir_dir}/"):
        rel_inside = Path(ir_rel).relative_to(ir_dir).with_suffix(".feature")
        return f"{features_dir}/{rel_inside.as_posix()}"
    return f"{features_dir}/{Path(ir_rel).with_suffix('.feature').name}"


def generate(ir_path: str, output_dir: str, feature_path: str | None = None) -> int:
    """Generate acceptance test entry points from JSON IR."""
    ir_file = Path(ir_path)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    root = _project_root(ir_file if ir_file.is_absolute() else Path.cwd())

    with open(ir_file) as handle:
        ir = json.load(handle)

    feature_name = ir.get("name", "unknown")
    ir_rel = _relative_ir_path(ir_file, root)
    resolved_feature = _feature_path_for(ir_rel, feature_path)
    paths = artifact_paths(resolved_feature)
    test_file = out_dir / Path(paths.test_path).name

    test_code = f'''"""Generated acceptance test for {feature_name}.

This file is auto-generated by the acceptance entrypoint generator.
Do not edit manually; regenerate from the JSON IR.
"""

import sys
from pathlib import Path

_PROJECT_ROOT = next(p for p in Path(__file__).resolve().parents if (p / "pyproject.toml").is_file())
_ACCEPTANCE_DIR = _PROJECT_ROOT / "acceptance"
sys.path.insert(0, str(_ACCEPTANCE_DIR))
sys.path.insert(0, str(_PROJECT_ROOT))

from acceptance_runtime import execute_ir


def test_acceptance():
    """Run all acceptance scenarios from the IR."""
    ir_path = _PROJECT_ROOT / "{paths.ir_path}"
    passed, output = execute_ir(str(ir_path))
    print(output)
    assert passed, f"Acceptance tests failed:\\n{{output}}"


if __name__ == "__main__":
    ir_path = _PROJECT_ROOT / "{paths.ir_path}"
    passed, output = execute_ir(str(ir_path))
    print(output)
    sys.exit(0 if passed else 1)
'''

    test_file.write_text(test_code)

    feature_abs = root / resolved_feature
    feature_hash = (
        _sha256_bytes(feature_abs.read_bytes())
        if feature_abs.is_file()
        else _sha256_bytes(b"")
    )

    meta = {
        "schema_version": 1,
        "feature_path": paths.feature_path,
        "ir_path": paths.ir_path,
        "feature_hash": feature_hash,
        "implementation_hash": _sha256_bytes(test_file.read_bytes()),
        "hash_scope": "generated_files",
        "generated_files": [test_file.name],
    }

    meta_dir = out_dir / "metadata"
    meta_dir.mkdir(parents=True, exist_ok=True)
    meta_file = meta_dir / metadata_name(resolved_feature)
    meta_file.write_text(json.dumps(meta, indent=2) + "\n")

    return 0


if __name__ == "__main__":
    if len(sys.argv) not in {3, 4}:
        print(
            "Usage: generate_entrypoints.py <json-ir> <generated-test-output> [feature-path]",
            file=sys.stderr,
        )
        sys.exit(2)
    feature = sys.argv[3] if len(sys.argv) == 4 else None
    sys.exit(generate(sys.argv[1], sys.argv[2], feature))
